name: Git to Notion Sync

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: NOTION_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tracker
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python tracker.py